In [39]:
# Qustion 3-Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
#Solution:
import numpy as np 
def vander_matrix(input_vector, n, increasing=False):
    
    if not increasing:
        output_matrix = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    elif increasing:
        output_matrix = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    
    return output_matrix
l=[5,6,7,8,9]
inputvector = np.array(l)
output_matrix_decreasing_order = vander_matrix(inputvector,5,False)
output_matrix_increasing_order = vander_matrix(inputvector,5,True)

print("The input array is:",inputvector,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_matrix_decreasing_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_matrix_increasing_order,"\n")


The input array is: [5 6 7 8 9] 

Vander matrix of the input array in decreasing order of powers:

 [[ 625  125   25    5    1]
 [1296  216   36    6    1]
 [2401  343   49    7    1]
 [4096  512   64    8    1]
 [6561  729   81    9    1]] 

Vander matrix of the input array in increasing order of powers:

 [[   1    5   25  125  625]
 [   1    6   36  216 1296]
 [   1    7   49  343 2401]
 [   1    8   64  512 4096]
 [   1    9   81  729 6561]] 

